{
 "title": "Air Quality",
 "description": "Air quality monitoring using AirGradient's DIY Basic sensors. See https://github.com/Machione/airgradient-prometheus for more information.",
 "tags": [ "AirGradient" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "PROMETHEUS_DEVICE_ID",
    "query": {
     "query": "label_values({sensor=\"airgradient\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$PROMETHEUS_DEVICE_ID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "PROMETHEUS_DEVICE_ID" },
  {
   "title": "Air Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "atmp{id=\"$PROMETHEUS_DEVICE_ID\", sensor=\"airgradient\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rhum{id=\"$PROMETHEUS_DEVICE_ID\", sensor=\"airgradient\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pm02{id=\"$PROMETHEUS_DEVICE_ID\", sensor=\"airgradient\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rco2{id=\"$PROMETHEUS_DEVICE_ID\", sensor=\"airgradient\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}